import { useState, useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useFeedbackStore } from "../stores/feedback-store";
import { useProjectStore } from "../stores/project-store";
import { useCoverageStore } from "../stores/coverage-store";
import { useUiStore } from "../stores/ui-store";
import {
  DEFAULT_COVERAGE_THRESHOLD,
  FEEDBACK_DEFAULT_DEPLOY_DIR,
  FEEDBACK_DEFAULT_FILENAME,
} from "@shared/constants";
import { useToast } from "../components/toast";

export function FeedbackPage(): JSX.Element {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const targetModuleId = searchParams.get("module");
  const [threshold, setThreshold] = useState(DEFAULT_COVERAGE_THRESHOLD);
  const structure = useProjectStore((s) => s.structure);
  const moduleCoverages = useCoverageStore((s) => s.moduleCoverages);
  const currentFeedback = useFeedbackStore((s) => s.currentFeedback);
  const enrichedGaps = useFeedbackStore((s) => s.enrichedGaps);
  const isGenerating = useFeedbackStore((s) => s.isGenerating);
  const generateFromData = useFeedbackStore((s) => s.generateFromData);
  const resetFeedback = useFeedbackStore((s) => s.reset);
  const deploy = useFeedbackStore((s) => s.deploy);
  const addLog = useUiStore((s) => s.addLog);

  const showToast = useToast((s) => s.show);
  const canGenerate = structure !== null && moduleCoverages.length > 0;
  const hasModule = !!targetModuleId;

  // ブロック図から特定モジュール指定で来た場合、自動生成（1回だけ）
  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (targetModuleId && canGenerate && structure && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      const filtered = moduleCoverages.filter(
        (mc) => mc.moduleId === targetModuleId,
      );
      if (filtered.length > 0) {
        generateFromData(structure, filtered, threshold);
        showToast(`${targetModuleId} のフィードバックを生成しました`);
      }
    }
  }, [targetModuleId]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleGenerate = (): void => {
    if (!structure || moduleCoverages.length === 0) {
      addLog(
        "warning",
        !structure
          ? "プロジェクトを先に読み込んでください。"
          : "カバレッジを先に取得してください。",
      );
      return;
    }

    if (targetModuleId) {
      const filtered = moduleCoverages.filter(
        (mc) => mc.moduleId === targetModuleId,
      );
      generateFromData(
        structure,
        filtered.length > 0 ? filtered : moduleCoverages,
        threshold,
      );
    } else {
      generateFromData(structure, moduleCoverages, threshold);
    }
    const gapCount = useFeedbackStore.getState().enrichedGaps.length;
    showToast(`フィードバックを生成しました（${gapCount}件）`);
  };

  const handleClear = (): void => {
    resetFeedback();
    setSearchParams({});
    addLog("info", "フィードバックをクリアしました");
  };

  const handleDeploy = async (): Promise<void> => {
    if (!structure || !currentFeedback) return;
    try {
      // enriched版JSONを構築して配置
      const enrichedJson = buildEnrichedJson(currentFeedback, enrichedGaps);
      const deployPath = `${structure.rootPath}/${FEEDBACK_DEFAULT_DEPLOY_DIR}/${FEEDBACK_DEFAULT_FILENAME}`;
      await window.api.feedback.deploy({
        feedbackFile: enrichedJson,
        deployPath,
      });
      showToast(`プロジェクトに配置しました: ${deployPath}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      showToast(message, "error");
    }
  };

  const handleCopyToClipboard = async (): Promise<void> => {
    if (!currentFeedback) return;
    const text = buildFeedbackText(currentFeedback, enrichedGaps);
    try {
      await navigator.clipboard.writeText(text);
      showToast("フィードバックをクリップボードにコピーしました");
    } catch {
      showToast("コピーに失敗しました", "error");
    }
  };

  // ボタンラベル
  const generateButtonLabel = isGenerating
    ? t("feedback.generating")
    : hasModule
      ? `${targetModuleId} フィードバック生成`
      : "全体のフィードバック生成";

  return (
    <div className="page feedback-page">
      <div className="feedback-toolbar">
        <h2 className="page-title">{t("feedback.title")}</h2>
        <div className="feedback-toolbar-right">
          <button
            className="btn btn-link"
            onClick={() => navigate("/feedback/history")}
          >
            {t("feedback.viewHistory")}
          </button>
        </div>
      </div>
      {!canGenerate && (
        <div className="feedback-hint-box">
          <p>
            {!structure
              ? "ホーム画面からプロジェクトを読み込んでください。"
              : "カバレッジ画面でテストを実行してカバレッジを取得してください。"}
          </p>
          <button
            className="btn btn-secondary"
            onClick={() => navigate(!structure ? "/" : "/coverage")}
          >
            {!structure ? "ホームへ" : "カバレッジ画面へ"}
          </button>
        </div>
      )}

      <div className="feedback-settings">
        <div className="feedback-settings-left">
          <div className="setting-group">
            <label>{t("feedback.threshold")}:</label>
            <input
              type="number"
              min={0}
              max={100}
              value={threshold}
              onChange={(e) => setThreshold(Number(e.target.value))}
            />
            <span>%</span>
          </div>
          <button
            className="btn btn-primary"
            onClick={handleGenerate}
            disabled={isGenerating || !canGenerate}
          >
            {generateButtonLabel}
          </button>
          {currentFeedback && (
            <button className="btn btn-secondary" onClick={handleClear}>
              クリア
            </button>
          )}
        </div>
        {currentFeedback && (
          <div className="feedback-export-buttons">
            <button
              className="btn btn-secondary"
              onClick={handleCopyToClipboard}
            >
              コピー
            </button>
            <button className="btn btn-primary" onClick={handleDeploy}>
              プロジェクトに配置
            </button>
          </div>
        )}
      </div>

      {currentFeedback && (
        <div className="feedback-result">
          <h3>{t("feedback.result")}</h3>
          <div className="feedback-summary">
            <div className="summary-item">
              <span className="summary-label">
                {t("feedback.totalModules")}
              </span>
              <span className="summary-value">
                {currentFeedback.summary.totalModules}
              </span>
            </div>
            <div className="summary-item">
              <span className="summary-label">
                {t("feedback.belowThreshold")}
              </span>
              <span className="summary-value summary-value--warn">
                {currentFeedback.summary.belowThreshold}
              </span>
            </div>
            <div className="summary-item">
              <span className="summary-label">
                {t("feedback.overallCoverage")}
              </span>
              <span className="summary-value">
                {currentFeedback.summary.overallCoverage.toFixed(1)}%
              </span>
            </div>
          </div>

          <h4>詳細分析 ({enrichedGaps.length} ファイル)</h4>
          <div className="enriched-gap-list">
            {enrichedGaps.map((gap) => (
              <div
                key={gap.filePath}
                className={`enriched-gap enriched-gap--${gap.priority}`}
              >
                <div className="eg-header">
                  <span className="eg-file">{gap.filePath}</span>
                  <span className={`eg-priority eg-priority--${gap.priority}`}>
                    {gap.priority.toUpperCase()} ({gap.priorityScore})
                  </span>
                  <span className="eg-test-type">
                    {gap.recommendedTestType}
                  </span>
                </div>

                <div className="eg-metrics">
                  <div className="eg-metric">
                    <span className="eg-metric-label">Line</span>
                    <div className="eg-metric-bar">
                      <div
                        className="eg-metric-fill"
                        style={{
                          width: `${gap.lineCoverage.percentage}%`,
                          background: barColor(gap.lineCoverage.percentage),
                        }}
                      />
                    </div>
                    <span className="eg-metric-val">
                      {gap.lineCoverage.percentage.toFixed(0)}% →{" "}
                      {gap.targetCoverage}%
                    </span>
                  </div>
                  {gap.branchCoverage && (
                    <div className="eg-metric">
                      <span className="eg-metric-label">Branch</span>
                      <div className="eg-metric-bar">
                        <div
                          className="eg-metric-fill"
                          style={{
                            width: `${gap.branchCoverage.percentage}%`,
                            background: barColor(gap.branchCoverage.percentage),
                          }}
                        />
                      </div>
                      <span className="eg-metric-val">
                        {gap.branchCoverage.percentage.toFixed(0)}% →{" "}
                        {gap.targetCoverage}%
                      </span>
                    </div>
                  )}
                  <div className="eg-metric">
                    <span className="eg-metric-label">Function</span>
                    <div className="eg-metric-bar">
                      <div
                        className="eg-metric-fill"
                        style={{
                          width: `${gap.functionCoverage.percentage}%`,
                          background: barColor(gap.functionCoverage.percentage),
                        }}
                      />
                    </div>
                    <span className="eg-metric-val">
                      {gap.functionCoverage.percentage.toFixed(0)}% →{" "}
                      {gap.targetCoverage}%
                    </span>
                  </div>
                  <div className="eg-metric">
                    <span className="eg-metric-label">品質</span>
                    <span
                      className={`eg-quality eg-quality--${gap.qualityLevel}`}
                    >
                      {gap.qualityLevel.toUpperCase()} ({gap.qualityScore}%)
                    </span>
                  </div>
                </div>

                {gap.uncoveredFunctions.length > 0 && (
                  <div className="eg-section">
                    <span className="eg-section-label">未テスト関数:</span>
                    <span className="eg-section-value">
                      {gap.uncoveredFunctions.join(", ")}
                    </span>
                  </div>
                )}

                {gap.uncoveredBranches.length > 0 && (
                  <div className="eg-section">
                    <span className="eg-section-label">未カバー分岐:</span>
                    <ul className="eg-branch-list">
                      {gap.uncoveredBranches.map((b, i) => (
                        <li key={i}>
                          L{b.line}: {b.condition}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {gap.requiredScenarios.length > 0 && (
                  <div className="eg-scenarios">
                    <span className="eg-section-label">
                      必要なテストシナリオ:
                    </span>
                    {gap.requiredScenarios.map((s, i) => (
                      <div
                        key={i}
                        className={`eg-scenario eg-scenario--${s.type}`}
                      >
                        <span className="eg-scenario-type">
                          {s.type === "normal"
                            ? "✓ 正常系"
                            : s.type === "error"
                              ? "✗ エラー系"
                              : "◇ 境界値"}
                        </span>
                        <span className="eg-scenario-desc">
                          {s.description}
                        </span>
                        <ul className="eg-scenario-assertions">
                          {s.assertions.map((a, j) => (
                            <li key={j}>{a}</li>
                          ))}
                        </ul>
                      </div>
                    ))}
                  </div>
                )}

                {gap.qualitySuggestions.length > 0 && (
                  <div className="eg-section eg-quality-suggestions">
                    <span className="eg-section-label">品質指摘:</span>
                    <ul>
                      {gap.qualitySuggestions.map((s, i) => (
                        <li key={i}>{s}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function barColor(pct: number): string {
  if (pct >= 80) return "#16a34a";
  if (pct >= 50) return "#ca8a04";
  return "#dc2626";
}

function buildFeedbackText(
  fb: import("@shared/types/feedback").FeedbackFile,
  gaps: readonly import("@shared/types/feedback-display").EnrichedGap[],
): string {
  const lines: string[] = [];
  lines.push("【Test Insight Hub フィードバック】");
  lines.push(
    `閾値: ${fb.coverageThreshold}% | 全体カバレッジ: ${fb.summary.overallCoverage.toFixed(1)}% | ギャップ: ${gaps.length}ファイル`,
  );
  lines.push(`生成日時: ${new Date(fb.generatedAt).toLocaleString()}`);
  lines.push("");

  for (const gap of gaps) {
    lines.push(
      `■ ${gap.filePath}  優先度: ${gap.priority.toUpperCase()} (${gap.priorityScore})  推奨: ${gap.recommendedTestType}`,
    );
    lines.push(
      `  Line: ${gap.lineCoverage.percentage.toFixed(0)}% → ${gap.targetCoverage}% | Function: ${gap.functionCoverage.percentage.toFixed(0)}% → ${gap.targetCoverage}%${gap.branchCoverage ? ` | Branch: ${gap.branchCoverage.percentage.toFixed(0)}% → ${gap.targetCoverage}%` : ""}`,
    );
    lines.push(
      `  品質: ${gap.qualityLevel.toUpperCase()} (${gap.qualityScore}%)`,
    );

    if (gap.uncoveredFunctions.length > 0) {
      lines.push(`  未テスト関数: ${gap.uncoveredFunctions.join(", ")}`);
    }

    if (gap.uncoveredBranches.length > 0) {
      lines.push("  未カバー分岐:");
      for (const b of gap.uncoveredBranches) {
        lines.push(`    L${b.line}: ${b.condition}`);
      }
    }

    if (gap.requiredScenarios.length > 0) {
      lines.push("  必要なテストシナリオ:");
      for (const s of gap.requiredScenarios) {
        const icon = s.type === "normal" ? "✓" : s.type === "error" ? "✗" : "◇";
        lines.push(`    ${icon} ${s.description}`);
        for (const a of s.assertions) {
          lines.push(`      → ${a}`);
        }
      }
    }

    if (gap.qualitySuggestions.length > 0) {
      lines.push("  品質指摘:");
      for (const s of gap.qualitySuggestions) {
        lines.push(`    ⚠ ${s}`);
      }
    }

    lines.push("");
  }

  lines.push("---");
  lines.push(
    "上記のフィードバックに従って、指摘されたファイルのテストを追加・改善してください。",
  );

  return lines.join("\n");
}

function buildEnrichedJson(
  fb: import("@shared/types/feedback").FeedbackFile,
  gaps: readonly import("@shared/types/feedback-display").EnrichedGap[],
): import("@shared/types/feedback").FeedbackFile {
  return {
    ...fb,
    gaps: gaps.map((g) => ({
      filePath: g.filePath,
      moduleName: g.moduleName,
      currentCoverage: g.lineCoverage.percentage,
      targetCoverage: g.targetCoverage,
      uncoveredLines: g.uncoveredBranches.map((b) => ({
        start: b.line,
        end: b.line,
        functionName: b.condition,
      })),
      recommendedTestType: g.recommendedTestType,
      priority: g.priority,
      priorityScore: g.priorityScore,
      complexity: g.complexity,
      changeFrequency: 0,
    })),
    recommendations: gaps.map((g) => ({
      type: g.recommendedTestType,
      targetFile: g.filePath,
      suggestedTestFile: "",
      functions: [...g.uncoveredFunctions],
      description: [
        `Line: ${g.lineCoverage.percentage.toFixed(0)}%→${g.targetCoverage}%`,
        `Function: ${g.functionCoverage.percentage.toFixed(0)}%→${g.targetCoverage}%`,
        g.branchCoverage
          ? `Branch: ${g.branchCoverage.percentage.toFixed(0)}%→${g.targetCoverage}%`
          : "",
        `品質: ${g.qualityLevel.toUpperCase()}`,
        ...g.requiredScenarios.map((s) => `${s.type}: ${s.description}`),
        ...g.qualitySuggestions.map((s) => `指摘: ${s}`),
      ]
        .filter(Boolean)
        .join(" | "),
    })),
  };
}
